name = "polyphony-registry"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "polyphony-registry-db"
database_id = "1b804304-94ad-4e32-ade4-9b3c363e3c48"
