name = "polyphony-registry"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "polyphony-registry-db"
database_id = "placeholder-create-with-wrangler"
